# Generated by Django 5.1.1 on 2024-10-31 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_remove_servicio_descripcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_comida', models.CharField(max_length=255)),
                ('categoria', models.CharField(max_length=255)),
                ('subcategoria', models.CharField(blank=True, max_length=255, null=True)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('peso', models.CharField(blank=True, max_length=50, null=True)),
                ('insumos', models.CharField(blank=True, max_length=255, null=True)),
                ('stock', models.IntegerField()),
                ('fecha_promocion_inicio', models.DateField(blank=True, null=True)),
                ('fecha_promocion_final', models.DateField(blank=True, null=True)),
                ('precio_anterior', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('descuento', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('precio_oferta', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('video', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
