# Generated by Django 5.1.1 on 2024-11-07 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0003_rest_delete_servicio'),
    ]

    operations = [
        migrations.AddField(
            model_name='rest',
            name='imagen_opcional1',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AddField(
            model_name='rest',
            name='imagen_opcional2',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AddField(
            model_name='rest',
            name='imagen_principal',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
        migrations.AddField(
            model_name='rest',
            name='imagen_secundaria',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes/'),
        ),
    ]
